packages:
  - "apps/**"
  - "packages/**"

catalog:
  typegpu: ^0.6.0
  unplugin-typegpu: https://pkg.pr.new/software-mansion/TypeGPU/unplugin-typegpu@3e953c02b1885c6528870b4dbf004b88eccde52c
  "@webgpu/types": ^0.1.64

catalogs:
  build:
    tsdown: ^0.12.9
    unplugin-auto-import: ^19.3.0
