packages:
  - "apps/**"
  - "packages/**"

catalog:
  typegpu: https://pkg.pr.new/software-mansion/TypeGPU/typegpu@5fb9a434e8c8b0287fce9e03e824a02f6599fb62
  unplugin-typegpu: 0.2.2
  "@webgpu/types": ^0.1.64

catalogs:
  build:
    tsdown: ^0.12.9
    unplugin-auto-import: ^19.3.0
