packages:
  - apps/**
  - packages/**

catalog:
  '@typegpu/react': 0.12.0
  '@webgpu/types': ^0.1.68
  typegpu: 0.12.4
  typescript: npm:tsover@6.0.2
  unplugin-typegpu: ^0.12.3
  koota: 0.5.1

catalogs:
  build:
    tsdown: ^0.12.9
