packages:
  - "apps/**"
  - "packages/**"

catalog:
  typegpu: https://pkg.pr.new/software-mansion/TypeGPU/typegpu@7320da746159cbb45eede15be0188cd2a3a3af6d
  unplugin-typegpu: 0.2.2
  "@webgpu/types": ^0.1.64

catalogs:
  build:
    tsdown: ^0.12.9
    unplugin-auto-import: ^19.3.0
