/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const add: typeof import('typegpu/std')['add']
  const builtin: typeof import('typegpu/data')['builtin']
  const d: typeof import('typegpu/data')
  const dot: typeof import('typegpu/std')['dot']
  const f32: typeof import('typegpu/data')['f32']
  const i32: typeof import('typegpu/data')['i32']
  const mat4x4f: typeof import('typegpu/data')['mat4x4f']
  const max: typeof import('typegpu/std')['max']
  const mul: typeof import('typegpu/std')['mul']
  const normalize: typeof import('typegpu/std')['normalize']
  const std: typeof import('typegpu/std')
  const struct: typeof import('typegpu/data')['struct']
  const tgpu: typeof import('typegpu')['tgpu']
  const u32: typeof import('typegpu/data')['u32']
  const vec2f: typeof import('typegpu/data')['vec2f']
  const vec3f: typeof import('typegpu/data')['vec3f']
  const vec4f: typeof import('typegpu/data')['vec4f']
}
